sudo: false
language: php
php:
  - 5.5
  - 5.6
env:
  matrix:
    - MAGENTO_VERSION=magento-ce-1.9.1.1
    - MAGENTO_VERSION=magento-ce-1.9.1.0
    - MAGENTO_VERSION=magento-ce-1.9.0.1
branches:
  except:
    - /^(\d+\.)+\d+$/
before_script:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
script:
  # Code Style
  - php phpcs.phar --standard=./phpcs.xml --encoding=utf-8 --report-width=180 ./app
  # Unit Tests
  - bash ./run_tests.sh
notifications:
  email:
    recipients: [ lee.saferite@aoe.com ]
    on_success: always
    on_failure: always
