<?php /** @var Aoe_Layout_Block_Widget_Container $this */ ?>
<?php echo $this->getBeforeScripts() ?>

<div class="content-header">
    <?php echo $this->getHeaderHtml() ?>
    <p class="form-buttons"><?php echo $this->getButtonsHtml('header') ?></p>
</div>

<?php echo $this->getChildHtml('', true, true); ?>

<?php if ($this->hasFooterButtons()): ?>
    <div class="content-footer">
        <p class="form-buttons"><?php echo $this->getButtonsHtml('footer') ?></p>
    </div>
<?php endif; ?>

<?php echo $this->getAfterScripts() ?>
